# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import sphinx_rtd_theme
sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Athena Docs'
copyright = '2020, Alex'
author = 'Alex'

# The full version, including alpha/beta/rc tags
release = '0.0.1'


# GENERAL CONFIGURATION

# 1. LOAD EXTENSIONS
#
# Add any Sphinx extension module names here, as strings. They
# can be extensions coming with Sphinx (named 'sphinx.ext.*') or
# your custom ones.

extensions = [
    "sphinx_rtd_theme",
    "sphinx.ext.extlinks",
    "sphinx.ext.todo",
    "sphinx.ext.autodoc",
    "sphinxcontrib.programoutput",
    "sphinx.ext.imgconverter",
]

# 1.1 Extensions Configuration

# -------------  extlinks  -----------------------------------
# Aυτή τη ρύθμιση τη βρήκα στο
# https://github.com/sphinx-doc/sphinx/blob/3.x/doc/conf.py
# από το ίδιο το sphinx

extlinks = {
'duref': ('http://docutils.sourceforge.net/docs/ref/rst/'
                      'restructuredtext.html#%s', ''),
 
'durole': ('http://docutils.sourceforge.net/docs/ref/rst/'
                       'roles.html#%s', ''),
 
'dudir': ('http://docutils.sourceforge.net/docs/ref/rst/'
                      'directives.html#%s', ''),
 
'wiki': ('https://en.wikipedia.org/wiki/%s', ''),
 
'pywiki': ('https://wiki.python.org/moin/%s', ''),
 
'pyorg': ('https://docs.python.org/3/%s', ''),

'texinfo': ('http://tug.org/texinfohtml/latex2e.html#%s', ''),

'texpkg': ('https://ctan.org/pkg/%s', '')
            }


# -------------  extlinks  -----------------------------------

todo_include_todos = True



# 2. DECLARE PATHS
#
# 2.1 Templates
#
# Add any paths that contain templates here, relative to this
# directory.

templates_path = ['_templates']


# 2.2 Static Content
#
# Add any paths that contain custom static files (such as style
# sheets) here, relative to this directory. They are copied after
# the builtin static files, so a file named "default.css" will
# overwrite the builtin "default.css".
html_logo = '_static/athena.png'
html_static_path = ['_static']

html_context = {
    'css_files': [
        
        # override wide tables in RTD theme
        '_static/css/theme_overrides.css',
        
     
        ],
     }

# 3. MASTER DOCUMENT CONFIG

"""
The language for content autogenerated by Sphinx.

Refer to documentation for a list of supported languages. This is
also used if you do content translation via gettext catalogs. 
Usually you set "language" from the command line for these cases.
"""

language = 'el'

#-----------------

"""
Pygment style
"""

pygments_style = 'sphinx'

#------------------

"""
Tells the project the name of the home page.
"""

master_doc = 'index'

#----------------

"""
Numbering figures an tables allover the document.
"""

numfig = True

numfig_format = {'figure': 'Εικ. %s', 'table': 'Πιν. %s',
                 'code-block': 'Κωδ. %s'}

#----------------------

"""
A string of reStructuredText that will be included at the
beginning of every source file that is read.
"""

rst_prolog = """
.. |latex| replace:: LaTeX
.. |tex| replace:: TeX
.. |euro| unicode:: U+20AC .. EURO SIGN

"""

#----------------- 

# 4. HTML OUTPUT CONFIG
#
# 4.1 HTML Theme
# The theme to use for HTML and HTML Help pages. See the
# documentation for a list of builtin themes.

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'prev_next_buttons_location': 'both',
    'style_external_links': False,
    'style_nav_header_background': 'white',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
    'style_external_links': True,
}

# 4.2 HTML Various
#
# 4.2.1 Compact lists

html_compact_lists = True

# 4.2.2 Exclutions
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.

exclude_patterns = []


# 5. LATEX OUTPUT CONFIG
#
# 5.1       .tex file output

latex_engine = 'xelatex'

latex_show_urls = 'no' # εναλλακτικά 'footnote', 'inline'

#latex_toplevel_sectioning = 'part'

latex_show_pagerefs = False

latex_additional_files = ['mystyle.tex.txt']


latex_elements = {
    
    'preamble': r'\input{mystyle.tex.txt}',

 #   'maketitle': r'\\sphinxmaketitle',
    
    'fontpkg': r'''
\setmainfont{Lato}
\setsansfont{DejaVu Sans}
\setmonofont{Consolas}
''',
    
    'papersize': 'a4paper',
    
    'tableofcontents': '\\sphinxtableofcontents',
    
    'fncychap': r'\usepackage[Sonny]{fncychap}',
    # εναλλακτικά: Bjornstrup, Bjornstrup, Lenny, Glenn, Conny,
    # Renje, Sonny

    'printindex': r'\footnotesize\raggedright\printindex',

    'sphinxsetup': 'verbatimwithframe=false',

    
}



# 5.2       .pdf file output

latex_documents = [
  ('latex/index', 'LatexGuide.tex', f'Latex Guide', u'Alex', 'manual'),
  ('rest/index', 'RestGuide.tex', f'RestructuredText Guide', u'Alex', 'manual'),
]


